spring:
  mvc:
    view:
      #配置Jsp视图前后缀
      #当项目作为SpringBoot模块子项目时，需要去Run Configurations里面配置Working Dirktory，
      #否则项目里面配置的很多路径都会从SpringBoot主项目开始找
      prefix: /
      suffix: .jsp
  #开启freemarker支持
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

  #设置上传文件的单个最大大小限制和单次请求最大大小限制
  #SpringBoot1.0中这些属性在http下，SpringBoot2.0这些属性在servlet下
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB


  #配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mmall?characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root

    #添加Druid配置
    type: com.alibaba.druid.pool.DruidDataSource
    #配置监控统计拦截的filters，去掉后在监控界面会无法统计SQL，
    filters: stat,wall,log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #连接等待超时最大时间
    maxWait: 60000
    #打开PSCache
    poolPreparedStatements: true
    #指定每一个连接的PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过ConnectionProperties打开mergeSQL功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=true
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false


  #配置SpringBoot下的SpringData的JPA
  jpa:
    database: MySQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    #默认开启，在事务外也可以访问懒加载的数据
    open-in-view: false


server:
  #更改访问端口
  port: 8081